"""Typed error models derived from the packaged OpenAPI projection.

The projection is generated by scripts.generate_error_contract, with byte parity
checked against the authoritative specification. No checkout paths are read at
runtime; the resource ships alongside this module in wheels and containers.
"""

import copy
import re
from functools import lru_cache
from typing import Annotated, Any, Literal, Self, Union

from pydantic import BaseModel, ConfigDict, Field, RootModel, model_validator

from sage.models._error_contract import SCHEMAS

META_KEY = "org.sage/errorSchema"
CODE_SCHEMAS = SCHEMAS["ErrorResponse"]["discriminator"]["mapping"]


def build_models(read_meta: type[BaseModel]) -> dict[str, type[BaseModel]]:
    """Derive strict Pydantic field types and envelope variants from schema nodes."""
    from pydantic import create_model

    models = {"ReadMeta": read_meta}

    def annotation(schema: dict, name: str) -> Any:
        if "$ref" in schema:
            return model(schema["$ref"].rsplit("/", 1)[-1])
        if "const" in schema:
            return Literal[schema["const"]]
        if "oneOf" in schema or "anyOf" in schema:
            return Union[
                tuple(
                    annotation(s, name + str(i))
                    for i, s in enumerate(schema.get("oneOf", schema.get("anyOf")))
                )
            ]
        kind = schema.get("type")
        if isinstance(kind, list):
            return Union[tuple(annotation({**schema, "type": k}, name) for k in kind)]
        if kind == "array":
            return list[annotation(schema.get("items", {}), name + "Item")]
        if kind == "object" and "maxProperties" in schema:
            return Annotated[dict[str, Any], Field(max_length=schema["maxProperties"])]
        if kind == "object" and "properties" in schema:
            return object_model(name, schema)
        return {
            "string": str,
            "integer": int,
            "number": float,
            "boolean": bool,
            "null": type(None),
            "object": dict[str, Any],
        }.get(kind, Any)

    def object_model(name: str, schema: dict) -> type[BaseModel]:
        fields = {}
        for key, prop in schema.get("properties", {}).items():
            field_type = annotation(prop, name + key.title())
            if key == "read_meta":
                default = Field(
                    default_factory=lambda: read_meta(success=False, body_present=False),
                    description=prop.get("description", "Self-describing read markers."),
                )
            else:
                default = Field(
                    default=... if key in schema.get("required", []) else None,
                    description=prop.get("description", "Additional context for this refusal."),
                )
            if name == "ExtensionError" and key == "code":
                default = Field(
                    description=prop.get("description"),
                    json_schema_extra={"not": {"enum": sorted(CODE_SCHEMAS)}},
                )
            fields[key] = (field_type, default)
        config = ConfigDict(
            strict=True, extra="forbid" if schema.get("additionalProperties") is False else "allow"
        )
        validators = {}
        if name == "ExtensionError":

            @model_validator(mode="after")
            def extension_only(self) -> Self:
                if self.code in CODE_SCHEMAS:
                    raise ValueError("known error codes must use their declared family")
                return self

            validators["extension_only"] = extension_only
        return create_model(name, __config__=config, __validators__=validators, **fields)

    def model(name: str) -> type[BaseModel]:
        if name in models:
            return models[name]
        schema = SCHEMAS[name]
        if "patternProperties" in schema:
            # The rejected digest key names the original per-file location.
            # Its value is arbitrary JSON; the key's grammar and expected text
            # remain strict. It is deliberately not a successful-input model.
            class LocatedDigestDetail(RootModel[dict[str, Any]]):
                root: dict[str, Any] = Field(description=schema.get("description"))

                @classmethod
                def __get_pydantic_json_schema__(cls, core_schema: Any, handler: Any) -> dict:
                    return copy.deepcopy(schema)

                @classmethod
                def model_json_schema(cls, **kwargs: Any) -> dict:
                    return copy.deepcopy(schema)

                @model_validator(mode="after")
                def valid_location(self) -> Self:
                    value = self.root
                    patterns = tuple(schema["patternProperties"])
                    if len(value) != 2 or not isinstance(value.get("expected"), str):
                        raise ValueError(
                            "digest detail requires expected and one rejected location"
                        )
                    keys = set(value) - {"expected"}
                    if not all(
                        k == "sha256" or any(re.fullmatch(p, k) for p in patterns) for k in keys
                    ):
                        raise ValueError("invalid digest detail location")
                    return self

            result = type(name, (LocatedDigestDetail,), {})
        elif "oneOf" in schema:
            result = create_model(
                name,
                __base__=RootModel[annotation(schema, name)],
                root=(annotation(schema, name), Field(description=schema.get("description"))),
            )
        else:
            result = object_model(name, schema)
        models[name] = result
        return result

    for name in SCHEMAS:
        if name != "ErrorResponse":
            model(name)
    return models


def select_detail(code: str, detail: Any, models: dict) -> Any:
    """Validate only the selected family; no other branch may rescue bad detail."""
    ref = CODE_SCHEMAS.get(code)
    if ref is None:
        return detail
    envelope = SCHEMAS[ref.rsplit("/", 1)[-1]]
    schema = envelope["properties"]["detail"]
    if "$ref" not in schema:
        if "anyOf" in schema:
            envelope_model = models[ref.rsplit("/", 1)[-1]]
            return envelope_model.model_validate(
                {"code": code, "message": "", "detail": detail}
            ).detail
        if detail not in (None, {}):
            raise ValueError(f"{code} does not carry detail")
        return detail
    return models[schema["$ref"].rsplit("/", 1)[-1]].model_validate(detail)


@lru_cache(maxsize=256)
def tool_error_schema(description: str, tool_name: str = "") -> dict:
    """Publish explicitly declared tool families, independent of narrative prose.

    The authoritative table includes boundary, service and delegated/callback
    refusals. An unregistered tool fails rather than receiving a partial schema.
    """
    codes = SCHEMAS["ErrorResponse"]["x-mcp-tool-errors"][tool_name]
    definitions = {}

    def local(node: Any) -> Any:
        if isinstance(node, list):
            return [local(v) for v in node]
        if not isinstance(node, dict):
            return node
        if "$ref" in node:
            name = node["$ref"].rsplit("/", 1)[-1]
            if name not in definitions:
                definitions[name] = {}
                body = copy.deepcopy(SCHEMAS[name])
                if name.endswith("Error"):
                    body["properties"]["error"] = body["properties"].pop("code")
                    body["properties"].pop("read_meta", None)
                    body["required"] = ["error" if x == "code" else x for x in body["required"]]
                definitions[name] = local(body)
            return {"$ref": "#/$defs/" + name}
        return {k: local(v) for k, v in node.items()}

    choices = [local({"$ref": CODE_SCHEMAS[code]}) for code in sorted(codes)]
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "oneOf": choices,
        "$defs": definitions,
        "discriminator": {
            "propertyName": "error",
            "mapping": {code: choices[i]["$ref"] for i, code in enumerate(sorted(codes))},
        },
    }
