"""One-off A/B for the new abstractor prompt.

Reads the seven Editorial Guidelines documents from the theology vault,
fetches their existing (old-prompt) semantic_abstract from the graph
store, reconstructs projection text from LanceDB chunks, runs the new
Qwen3 abstractor against each, and writes a side-by-side report.

Does NOT modify stored state. Pure read + new generation + report.
"""

import asyncio
import sqlite3
import sys
from pathlib import Path
from textwrap import indent

from sage.adapters.abstraction_qwen3 import Qwen3AbstractionProvider
from sage.adapters.content_store_lancedb import LanceDBContentStore
from sage.adapters.abstraction_utils import (
    compute_max_tokens,
    trim_to_sentence_boundary,
)
from sage.config import AbstractionConfig

VAULT_BRAIN = Path.home() / "sage_vaults" / "theology" / "brain"
GRAPH_DB = VAULT_BRAIN / "graph.db"
QWEN_MODEL_ID = "mlx-community/Qwen3-30B-A3B-Instruct-2507-4bit"

# Seven docs, in the order Clif described in the failure report
DOC_IDS = [
    ("5e66ecd3_genre_guidelines_pastoral", "Pastoral"),
    ("e380e172_genre_guidelines_blog_devotional", "Blog / Devotional"),
    ("0d7f99ba_genre_guidelines_public_writing", "Public Writing"),
    ("4d803965_genre_guidelines_church_leadership_executive",
     "Church Leadership / Executive"),
    ("322c51df_genre_guidelines_academic_theology", "Academic Theology"),
    ("fbd68861_editorial_guidelines_for_ai_amanuenses",
     "Editorial Guidelines (master)"),
    ("da751867_genre_guidelines_social_media",
     "Social Media (control: was clean)"),
]

ABSTRACTION_CONFIG = AbstractionConfig(
    enabled=True,
    model=QWEN_MODEL_ID,
    max_abstract_tokens=500,  # Matches the theology vault config
    base_abstract_tokens=150,
    tokens_per_word=0.02,
)


def fetch_doc_record(conn: sqlite3.Connection, doc_id: str) -> dict:
    cur = conn.execute(
        "SELECT id, title, doc_type, semantic_abstract FROM documents "
        "WHERE id = ?",
        (doc_id,),
    )
    row = cur.fetchone()
    if row is None:
        raise SystemExit(f"Document not found: {doc_id}")
    return {
        "id": row[0],
        "title": row[1],
        "doc_type": row[2],
        "old_abstract": row[3] or "(none)",
    }


async def main() -> int:
    if not GRAPH_DB.exists():
        print(f"ERROR: graph store not found at {GRAPH_DB}", file=sys.stderr)
        return 1

    conn = sqlite3.connect(GRAPH_DB)
    content_store = LanceDBContentStore(brain_root=VAULT_BRAIN)
    provider = Qwen3AbstractionProvider(model_id=QWEN_MODEL_ID)

    out_lines: list[str] = []
    out_lines.append("# A/B: Editorial Guidelines abstracts (old vs new prompt)\n")
    out_lines.append(
        "Generated by `scripts/ab_editorial_guidelines.py` against the "
        "theology vault. The OLD column is the stored `semantic_abstract` "
        "produced under the old prompt. The NEW column is generated "
        "in-process by the new prompt against the same projection text. "
        "Stored state is not modified.\n"
    )

    for doc_id, label in DOC_IDS:
        print(f"[*] {label} ({doc_id})", file=sys.stderr)
        rec = fetch_doc_record(conn, doc_id)

        chunks = await content_store.get_all_chunks(doc_id)
        projection_text = "\n\n".join(c.content for c in chunks)

        word_count = len(projection_text.split())
        max_tokens = compute_max_tokens(word_count, ABSTRACTION_CONFIG)
        print(
            f"    chunks={len(chunks)} words={word_count} "
            f"max_tokens={max_tokens} doc_type={rec['doc_type']!r}",
            file=sys.stderr,
        )

        raw_new = await provider.generate_abstract(
            projection_text, max_tokens, rec["doc_type"]
        )
        new_abstract = trim_to_sentence_boundary(raw_new)

        out_lines.append(f"\n---\n\n## {label}\n")
        out_lines.append(f"- **Title:** {rec['title']}")
        out_lines.append(f"- **doc_type:** `{rec['doc_type']}`")
        out_lines.append(f"- **Document id:** `{doc_id}`")
        out_lines.append(
            f"- **Source words:** {word_count}  |  "
            f"**max_tokens:** {max_tokens}\n"
        )
        out_lines.append("### OLD (stored) abstract\n")
        out_lines.append("> " + rec["old_abstract"].replace("\n", "\n> "))
        out_lines.append("\n### NEW abstract (descriptive, doc_type-aware)\n")
        out_lines.append("> " + new_abstract.replace("\n", "\n> "))

    report_path = (
        Path(__file__).parent.parent
        / "ab_editorial_guidelines_report.md"
    )
    report_path.write_text("\n".join(out_lines) + "\n")
    print(f"\nReport written to {report_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
